name: learn_henna
description: Application d’apprentissage du henné

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.5
  provider: ^6.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.1
  youtube_player_flutter: ^8.1.1
video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    
